"""modo ensaio e liberacao por categoria

Revision ID: 39eeedd904b1
Revises: dd961064ddd0
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39eeedd904b1'
down_revision: Union[str, None] = 'dd961064ddd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liberacao_categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('liberada', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('liberada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liberada_por', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria')
    )
    op.add_column('caso', sa.Column('em_ensaio', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('caso', sa.Column('aprovado_em_ensaio', sa.Boolean(), nullable=True))
    # Indice HNSW criado por SQL bruto; mantido de proposito.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caso', 'aprovado_em_ensaio')
    op.drop_column('caso', 'em_ensaio')
    op.drop_table('liberacao_categoria')
    # ### end Alembic commands ###
