"""trilha do atendimento humano e fontes usadas

Revision ID: 45d0bd370f61
Revises: cb9c47812a5d
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45d0bd370f61'
down_revision: Union[str, None] = 'cb9c47812a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caso', sa.Column('resposta_enviada', sa.Text(), nullable=True))
    op.add_column('caso', sa.Column('fontes_usadas', sa.JSON(), nullable=True))
    op.add_column('caso', sa.Column('assumido_por', sa.String(length=200), nullable=True))
    op.add_column('caso', sa.Column('assumido_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('caso', sa.Column('encerrado_em', sa.DateTime(timezone=True), nullable=True))
    # Indice HNSW criado por SQL bruto; o autogenerate propoe remove-lo
    # a cada revisao por nao conhece-lo. Mantido de proposito.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caso', 'encerrado_em')
    op.drop_column('caso', 'assumido_em')
    op.drop_column('caso', 'assumido_por')
    op.drop_column('caso', 'fontes_usadas')
    op.drop_column('caso', 'resposta_enviada')
    # ### end Alembic commands ###
