"""schema inicial das 12 entidades

Revision ID: 6872da03c2c5
Revises: 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '6872da03c2c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Busca semantica e dados relacionais no mesmo banco (secao 10):
    # menos pecas, menos falhas.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aresta_jornada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origem', sa.String(length=64), nullable=False),
    sa.Column('destino', sa.String(length=64), nullable=False),
    sa.Column('taxa_travamento', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aresta_origem_destino', 'aresta_jornada', ['origem', 'destino'], unique=True)
    op.create_table('curso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('prazo_conclusao', sa.Date(), nullable=False),
    sa.Column('modulos', sa.JSON(), nullable=False),
    sa.Column('webconferencias', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_conhecimento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('dono', sa.String(length=200), nullable=False),
    sa.Column('valido_ate', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=24), nullable=False),
    sa.Column('taxa_resolucao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ultima_citacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprovado_por_servidor', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=32), nullable=True),
    sa.Column('perfil', sa.String(length=24), nullable=False),
    sa.Column('canal_preferido', sa.String(length=24), nullable=False),
    sa.Column('nivel_identidade', sa.String(length=24), nullable=False),
    sa.Column('saldo_atencao', sa.Integer(), nullable=False),
    sa.Column('aceita_avisos', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('agrupamento_causa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rotulo', sa.String(length=300), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('aresta_origem_id', sa.UUID(), nullable=True),
    sa.Column('cursos_afetados', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aresta_origem_id'], ['aresta_jornada.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('vetor', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento_conhecimento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.String(length=24), nullable=False),
    sa.Column('handle_canal', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_proativo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gatilho', sa.String(length=64), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_esperado', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('hipotese', sa.Text(), nullable=False),
    sa.Column('verificar_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('efeito', sa.String(length=24), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('data_inscricao', sa.Date(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progresso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dois_fatores_configurado', sa.Boolean(), nullable=False),
    sa.Column('prazo_pessoal', sa.Date(), nullable=True),
    sa.Column('situacao_certificado', sa.String(length=24), nullable=False),
    sa.Column('aresta_atual_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aresta_atual_id'], ['aresta_jornada.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matricula_part_curso', 'matricula', ['participante_id', 'curso_id'], unique=True)
    op.create_table('caso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=True),
    sa.Column('conversa_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.String(length=24), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('sensivel', sa.Boolean(), nullable=False),
    sa.Column('confianca', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decisao_triagem', sa.String(length=32), nullable=True),
    sa.Column('situacao', sa.String(length=24), nullable=False),
    sa.Column('dossie', sa.JSON(), nullable=True),
    sa.Column('rascunho_resposta', sa.Text(), nullable=True),
    sa.Column('contrato_resolucao', sa.String(length=24), nullable=False),
    sa.Column('contrato_perguntado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orientacao_padrao_falhou', sa.Boolean(), nullable=False),
    sa.Column('score_consequencia', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duplicado_de_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicado_de_id'], ['caso.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversa_id', sa.UUID(), nullable=False),
    sa.Column('direcao', sa.String(length=16), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('acoes_rapidas', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_correcao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agrupamento_id', sa.UUID(), nullable=True),
    sa.Column('hipotese', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('previsao_queda_mensal', sa.Integer(), nullable=False),
    sa.Column('medir_em', sa.Date(), nullable=True),
    sa.Column('resultado_medido', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=24), nullable=False),
    sa.Column('impacto_estimado', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agrupamento_id'], ['agrupamento_causa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caso_id', sa.UUID(), nullable=True),
    sa.Column('etapa', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Secao 7.5 — log imutavel. Requisito nao negociavel em ambiente
    # judiciario, e por isso e imposto pelo banco, nao por disciplina da
    # aplicacao: mesmo um bug no motor nao consegue reescrever a auditoria.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION farol_log_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'log_auditoria e append-only: % negado', TG_OP;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER log_auditoria_append_only
        BEFORE UPDATE OR DELETE ON log_auditoria
        FOR EACH ROW EXECUTE FUNCTION farol_log_append_only();
        """
    )

    # Indice vetorial para a recuperacao semantica (Fase 1).
    op.execute(
        "CREATE INDEX ix_chunk_vetor ON chunk "
        "USING hnsw (vetor vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_chunk_vetor")
    op.execute("DROP TRIGGER IF EXISTS log_auditoria_append_only ON log_auditoria")
    op.execute("DROP FUNCTION IF EXISTS farol_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_auditoria')
    op.drop_table('ordem_correcao')
    op.drop_table('mensagem')
    op.drop_table('caso')
    op.drop_index('ix_matricula_part_curso', table_name='matricula')
    op.drop_table('matricula')
    op.drop_table('evento_proativo')
    op.drop_table('conversa')
    op.drop_table('chunk')
    op.drop_table('agrupamento_causa')
    op.drop_table('participante')
    op.drop_table('documento_conhecimento')
    op.drop_table('curso')
    op.drop_index('ix_aresta_origem_destino', table_name='aresta_jornada')
    op.drop_table('aresta_jornada')
    # ### end Alembic commands ###
