"""estado do fluxo guiado na conversa

Revision ID: cb9c47812a5d
Revises: 6872da03c2c5
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb9c47812a5d'
down_revision: Union[str, None] = '6872da03c2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # O indice HNSW e criado por SQL bruto e nao consta no metadata; o
    # autogenerate propoe remove-lo a cada revisao. Mantido de proposito.
    op.add_column('conversa', sa.Column('fluxo_estado', sa.JSON(), nullable=True))
    op.add_column('conversa', sa.Column('contexto_pagina', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversa', 'contexto_pagina')
    op.drop_column('conversa', 'fluxo_estado')
    # ### end Alembic commands ###
