"""pergunta e vetor no caso, medicao na ordem

Revision ID: dd961064ddd0
Revises: 45d0bd370f61
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'dd961064ddd0'
down_revision: Union[str, None] = '45d0bd370f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caso', sa.Column('pergunta', sa.Text(), nullable=True))
    op.add_column('caso', sa.Column('vetor_pergunta', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('caso', sa.Column('agrupamento_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'caso', 'agrupamento_causa', ['agrupamento_id'], ['id'], ondelete='SET NULL')
    # Indice HNSW criado por SQL bruto; mantido de proposito.
    op.add_column('ordem_correcao', sa.Column('volume_base_mensal', sa.Integer(), nullable=False))
    op.add_column('ordem_correcao', sa.Column('implementada_em', sa.Date(), nullable=True))
    op.add_column('ordem_correcao', sa.Column('conclusao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordem_correcao', 'conclusao')
    op.drop_column('ordem_correcao', 'implementada_em')
    op.drop_column('ordem_correcao', 'volume_base_mensal')
    op.drop_constraint(None, 'caso', type_='foreignkey')
    op.drop_column('caso', 'agrupamento_id')
    op.drop_column('caso', 'vetor_pergunta')
    op.drop_column('caso', 'pergunta')
    # ### end Alembic commands ###
